# Generated by Django 4.1.6 on 2023-02-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('adresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('zeme', models.CharField(max_length=25)),
                ('mesto', models.CharField(max_length=55)),
                ('ulice', models.CharField(max_length=75)),
                ('cislo_popisne', models.IntegerField()),
                ('psc', models.CharField(max_length=6)),
                ('cislo_bytu', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dorucovatel',
            fields=[
                ('dorucovatel_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazevfirmy', models.CharField(db_column='NazevFirmy', max_length=32)),
                ('telefonni_cislo', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'dorucovatel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('kategorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_kategorie', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'kategorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KreditniKarta',
            fields=[
                ('karta_id', models.AutoField(primary_key=True, serialize=False)),
                ('cislo_karty', models.CharField(max_length=19)),
                ('expirace', models.CharField(max_length=5)),
                ('jmeno_karta', models.CharField(max_length=64)),
                ('prijmeni_karta', models.CharField(max_length=32)),
                ('cvc', models.IntegerField(db_column='CVC')),
            ],
            options={
                'db_table': 'kreditni_karta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('objednavka_id', models.AutoField(primary_key=True, serialize=False)),
                ('cislo_objednavky', models.CharField(max_length=8)),
                ('celkova_cena', models.FloatField(blank=True, null=True)),
                ('datum_koupe', models.DateField()),
                ('datum_odeslani', models.DateField(blank=True, null=True)),
                ('datum_doruceni', models.DateField(blank=True, null=True)),
                ('datum_zaplaceni', models.DateField(blank=True, null=True)),
                ('isdoruceno', models.IntegerField(blank=True, db_column='isDoruceno', null=True)),
                ('iszaplaceno', models.IntegerField(blank=True, db_column='isZaplaceno', null=True)),
            ],
            options={
                'db_table': 'objednavka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('platba_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ_platby', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'platba',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('produkt_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_produktu', models.CharField(max_length=64)),
                ('velikost', models.CharField(max_length=3)),
                ('barva', models.CharField(max_length=16)),
                ('kratky_popis', models.CharField(max_length=64)),
                ('dlouhy_popis', models.CharField(max_length=254)),
                ('obrazek', models.ImageField(upload_to='images/')),
                ('cena', models.FloatField()),
                ('pocet_kusu', models.IntegerField()),
            ],
            options={
                'db_table': 'produkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZakazikAccount',
            fields=[
                ('zakazik_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('uzivatelske_jmeno', models.CharField(max_length=64)),
                ('heslo', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'zakazik_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('zakaznik_id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=64)),
                ('prijmeni', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=256)),
                ('telefoni_cislo', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'zakaznik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProcentoProdukt',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aplikace.material')),
                ('proceto', models.FloatField()),
            ],
            options={
                'db_table': 'material_procento_produkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjednavkaProdukt',
            fields=[
                ('objednavka', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aplikace.objednavka')),
                ('kusu', models.IntegerField()),
            ],
            options={
                'db_table': 'objednavka_produkt',
                'managed': False,
            },
        ),
    ]
