# Generated by Django 4.1.6 on 2023-02-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosik',
            fields=[
                ('kosik_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kosik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KosikProdukt',
            fields=[
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aplikace.produkt')),
            ],
            options={
                'db_table': 'kosik_produkt',
                'managed': False,
            },
        ),
    ]
